image:
  file: .gitpod.Dockerfile

ports:
  # Rails server
  - port: 3000
    onOpen: open-preview
  # PostgreSQL server
  - port: 5432
    onOpen: ignore

tasks:
- init: >
    bundle install &&
    yarn install &&
    rails db:create
  command: >
    RAILS_DEVELOPMENT_HOSTS=3000-$GITPOD_WORKSPACE_ID.ws-us30.gitpod.io ./bin/dev

vscode:
  extensions:
    - rebornix.ruby
